### ISSUE TITLE
Deploy with image, errors on app creation, otherwise claims no image access

### ISSUE THREAD

**Issue by intel352** [digitalocean/app_action#130] opened 2024-08-09 05:14 UTC
When no app exists in DO acct, running v2 deploy of an app with 2 services and 1 worker outputs the following:
```
app "core" does not exist yet, creating...
Error: failed to deploy: failed to create app: POST https://api.digitalocean.com/v2/apps: 409 (request "7f835d38-a2a1-40cc-88af-5e10b37c9461") App name already exists
```

When I check DO account, the app now exists, just isn't deployed.

If I run the job again:
```
app "core" already exists, updating...
Error: failed to deploy: failed to update app: PUT https://api.digitalocean.com/v2/apps/cb57496e-ccb8-45a6-ae28-aced510f6084: 500 (request "ba74a02d-9e5c-4b61-bd76-1e5773d05c91") Server Error; giving up after 5 attempt(s)
```

Giving up without actual details regarding what the error was is pretty useless.
If I go into DO interface, and attempt to use the Deploy button on the app, it then claims it doesn't have access to the image.

Some details:
- I have a Github org that I created which my repo exists within
- The DO app is installed in my org
- I created a personal access token (classic) to provide explicit read access to packages. I then pass `user:token` as credentials to my app.yaml to ensure DO has access to the built images

Here is my app.yaml:
```
name: core
ingress:
  rules:
    - component:
        name: manager
      match:
        path:
          prefix: /
    - component:
        name: runner
      match:
        path:
          prefix: /runner
region: nyc
services:
  - name: manager
    image:
      registry_type: GHCR
      registry: gocodealone
      repository: core
      registry_credentials: ${GHCR_CREDS} 
      digest: ${MANAGER_DIGEST}
    http_port: 9999
  - name: runner
    image:
      registry_type: GHCR
      registry: gocodealone
      repository: core
      registry_credentials: ${GHCR_CREDS}
      digest: ${RUNNER_DIGEST}
    http_port: 8888
workers:
  - name: orchestrator
    image:
      registry_type: GHCR
      registry: gocodealone
      repository: core
      registry_credentials: ${GHCR_CREDS}
      digest: ${ORCHESTRATOR_DIGEST}
```

When the run executes, I can see that each digest is indeed passed in as expected, as are my credentials:
```
Run digitalocean/app_action/deploy@v2
  with:
    token: ***
    print_build_logs: true
    print_deploy_logs: true
    app_spec_location: .do/app.yaml
    deploy_pr_preview: false
  env:
    GHCR_CREDS: intel352:***
    ORCHESTRATOR_DIGEST: sha256:bd81c30f851ce56dead4c01c24ede3dcbd722e4f1bd533d5f1b634a8d64cfc83
    MANAGER_DIGEST: sha256:11793823ab088e39800ad460b553d8cc66ab4753ba2dd8e2ce7b37f3b20fa080
    RUNNER_DIGEST: sha256:f2f89e4c288ad9db47c72e3f1dd6ebfcde6aad3d35cd7e7f45555e767440c8ed
```

Additionally, when I specify the print*logs options, I see no change to the output... So there's no additional logging that is enabled to help debug the actual problem.

**Comment by markusthoemmes** [comment] 2024-08-09 06:32
On the first issue: Was the action running concurrently by chance? That one sounds like a potential race between 2 runs.

On the 2nd issue: I've looked into the respective backend logs and you indeed hit an internal server error here. That request did not raise the inability to reach the image. I'm going to dig more into why this one was happening.

Is the behaviour reproducible by chance?

**Comment by intel352** [comment] 2024-08-09 06:49
> On the first issue: Was the action running concurrently by chance? That one sounds like a potential race between 2 runs.
No, the prior steps are matrix, the final step is the deploy action which is a single action, no other runs active. I've reproduced this multiple times.

> On the 2nd issue: I've looked into the respective backend logs and you indeed hit an internal server error here. That request did not raise the inability to reach the image. I'm going to dig more into why this one was happening.
Hmm, okay, well, at least that bodes well for the action itself passing along the error correctly then?

> Is the behaviour reproducible by chance?
Yep, consistently.

Some additional details, this is a private repo, where I'm building images prior to triggering the deploy (and passing the digests). Multiple builds in the same repo, using same GHCR registry, but tagged uniquely per image, with a unique digest resulting for each image as well.

If you'd like to experiment with this workflow, let me know, I can give you access to my repo so that you can modify and execute in the course of troubleshooting

**Comment by markusthoemmes** [comment] 2024-08-09 07:01
So you can reproduce the "App name already exists" error? Or is it the "not being able to fetch the image part" that you can reproduce now?

**Comment by markusthoemmes** [comment] 2024-08-09 07:16
As to the GHCR authentication issues: Can you verify that the authentication works via a `docker pull` (or similar) on your local machine? Since the image lives in an organisation but your token is for your account, I wonder if something's amiss on that front.

**Comment by intel352** [comment] 2024-08-09 15:08
> So you can reproduce the "App name already exists" error? Or is it the "not being able to fetch the image part" that you can reproduce now?

Once the app is already created, just the second error becomes reproducible. If I delete the app from DO, then the first error is reproducible again for the first run.

> As to the GHCR authentication issues: Can you verify that the authentication works via a `docker pull` (or similar) on your local machine? Since the image lives in an organisation but your token is for your account, I wonder if something's amiss on that front.

Thanks for suggesting this, I rarely ever touch docker cli, esp for remote registries.

I registered a second token, performed a docker login, and then using manifest inspection:
```
(base) jon@Jonathans-MacBook-Pro phoenix-test-actor % docker manifest inspect ghcr.io/gocodealone/core
manifest unknown
```

I suspect the issue here is that I'm using named tags for each image. If I inspect using a tag reference, I get this:
```
(base) jon@Jonathans-MacBook-Pro phoenix-test-actor % docker manifest inspect ghcr.io/gocodealone/core:manager-branch-main
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1814,
         "digest": "sha256:cd091bd2d710dd2ae7a1de0074aff760b16ff515e59607a567c069d160ab634d",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:10004c07601d25f066f3a50e18fa9e4282b79c4a9bd5a7f3cbe73c774bd93c55",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

The digests that are reflected there do not match what was pushed in the last build:
```
#15 exporting to image
#15 pushing layers 2.3s done
#15 pushing manifest for ghcr.io/gocodealone/core:manager-git-commit-1e066742307e196fd0c686fcfa1ca1cd78951575@sha256:11793823ab088e39800ad460b553d8cc66ab4753ba2dd8e2ce7b37f3b20fa080
#15 pushing manifest for ghcr.io/gocodealone/core:manager-git-commit-1e066742307e196fd0c686fcfa1ca1cd78951575@sha256:11793823ab088e39800ad460b553d8cc66ab4753ba2dd8e2ce7b37f3b20fa080 1.2s done
#15 pushing layers 0.4s done
#15 pushing manifest for ghcr.io/gocodealone/core:manager-branch-main@sha256:11793823ab088e39800ad460b553d8cc66ab4753ba2dd8e2ce7b37f3b20fa080
#15 pushing manifest for ghcr.io/gocodealone/core:manager-branch-main@sha256:11793823ab088e39800ad460b553d8cc66ab4753ba2dd8e2ce7b37f3b20fa080 0.7s done
#15 DONE 9.7s
```

This is quite strange.
When I look at my docker images in the Packages of my repo, I do see the relevant digest ending `080`:
![Screenshot 2024-08-09 at 11 07 04 AM](https://github.com/user-attachments/assets/3fd522ad-3940-4c9c-a200-b335f550225d)

**Comment by markusthoemmes** [comment] 2024-08-09 16:00
Thanks, I'll look into that conflict issue, that one looks strange. To clarify my understanding: It only happens if you don't have any apps, right?

To the image thing: Have you tried `docker pull`ing the SHA directly? AFAIK the tag does not influence the SHA.

**Comment by intel352** [comment] 2024-08-09 17:51
This works:

```
docker pull --platform amd64 ghcr.io/gocodealone/core@sha256:8f48dc9e44d58aed4c2d04500c4428d1608fb9ca6c768c506713a9c777d72526
ghcr.io/gocodealone/core@sha256:8f48dc9e44d58aed4c2d04500c4428d1608fb9ca6c768c506713a9c777d72526: Pulling from gocodealone/core
c6a83fedfae6: Pull complete
e0ff4780a542: Pull complete
cd9d85f16f94: Pull complete
4a8a5fbb8e7f: Pull complete
b30beed2cff5: Pull complete
f5d74e30e309: Pull complete
433819d3b7c7: Pull complete
Digest: sha256:8f48dc9e44d58aed4c2d04500c4428d1608fb9ca6c768c506713a9c777d72526
Status: Downloaded newer image for ghcr.io/gocodealone/core@sha256:8f48dc9e44d58aed4c2d04500c4428d1608fb9ca6c768c506713a9c777d72526
ghcr.io/gocodealone/core@sha256:8f48dc9e44d58aed4c2d04500c4428d1608fb9ca6c768c506713a9c777d72526
```

I had to specify platform, otherwise it failed (I'm on a macbook pro, defaulted to arm64)

**Comment by markusthoemmes** [comment] 2024-08-12 08:02
@intel352 ok. And that same SHA with the same login credentials does not work against App Platform?

**Comment by intel352** [comment] 2024-08-13 07:09
> @intel352 ok. And that same SHA with the same login credentials does not work against App Platform?

Correct, pulled the sha from the most recent failed run. The credentials is a different set (same username, diff token). Both tokens were created the same way, as classic tokens, with the same access.

**Comment by markusthoemmes** [comment] 2024-08-14 16:13
@intel352 I see that you've actually managed to get the app to launch ('ish) 5 days ago already so I think we're not really talking about the same issues necessary here 🤔 . Do you mind opening a support ticket so we can get your specific issues ironed out?

**Comment by markusthoemmes** [comment] 2024-08-28 06:54
@intel352 looping back on this one, is there anything I can help with at this point?

**Comment by markusthoemmes** [comment] 2024-09-10 10:50
@intel352 I'll close this out for now as I can't reproduce and you seem to have succeeded at deploying eventually. Please let me know if the issue persists, we can reopen then.

**Closed by markusthoemmes** 2024-09-10 10:50 UTC
